### ISSUE TITLE
Cameroon flag breaks when used inside tablesort tables

### ISSUE THREAD

**Issue by BrekiTomasson** [agatanga/flags#2] opened 2022-10-08 18:46 UTC
This is an edge-case, I know, but it's a weird one that I haven't been able to resolve in any meaningful way. When I put the flag of Cameroon inside a cell of a table that is then sortable using the javascript `tablesort` library, sometimes the flag becomes all-yellow. When inspecting the element, it appears the yellow star in the flag has grown out of proportion and is taking up more space than the entire flag. If I delete the entire `<g fill="#fcd116" [...]>` element, the flag comes back, but without the yellow star in the middle. Similarly, if I reduce the scale, which defaults to 7.1111, to something like 0.4, it looks all right again.

My guess is that there's something going on here where the svg is unable to figure out its 'actual' size while the table is being resorted, but I can't figure out why this is only affecting this particular flag and none of the others that have small stars in them.

**Comment by vovayatsyuk** [comment] 2022-10-08 20:29
Just tagged the new release with updated icons. Try to update, maybe new icons will fix the issue.

**Comment by BrekiTomasson** [comment] 2022-10-08 21:08
Nope, problem remains after updating to `v1.0.6`, unfortunately.

Cameroon's flag normally:

![image](https://user-images.githubusercontent.com/7026735/194727812-57f2d65a-2448-4ddb-84b3-9d01e054b6f6.png)

Cameroon's flag after changing sort order of the table:

![image](https://user-images.githubusercontent.com/7026735/194727836-8719dea5-0883-4241-b568-a8bcedef338c.png)

Hovering over the `<g fill="#fcd116" [...]>` element when flag is as intended:

![image](https://user-images.githubusercontent.com/7026735/194727874-34553aab-1e5c-4974-94ae-a60ded4b29c0.png)

Hovering over the `<g fill="#fcd116" [...]>` element when flag is in broken state:

![image](https://user-images.githubusercontent.com/7026735/194727861-0955ed00-f40d-4f7a-b418-ef3322d8b19b.png)

**Comment by vovayatsyuk** [comment] 2022-10-09 09:32
I was able to reproduce similar issue at codepen. Looks like an issue caused by duplicated ids in these flags.

Codepen with sortable table: https://codepen.io/vovayatsyuk/pen/eYrPXgW?editors=1000

1. At the initial page load, the Honduras flag is corrupted.
2. When changing sort order by clicking on the table header Cameroon and Indian flags get corrupted.

**Comment by vovayatsyuk** [comment] 2022-10-09 12:24
I've updated [codepen](https://codepen.io/vovayatsyuk/pen/eYrPXgW?editors=1000) with additional table where I've added `-COUNTRY_CODE` suffix to all ids.

Here is a result:

<img width="300" height="400" alt="Screenshot" src="https://user-images.githubusercontent.com/306080/194756444-6d9b0966-4cf7-4186-9099-801ae06190a2.png">

@lipis have you ever noticed such behaviour?

**Comment by BrekiTomasson** [comment] 2022-10-10 09:53
Good catch, I totally missed that one, but it makes a lot of sense in the context.

**Comment by vovayatsyuk** [comment] 2022-10-18 18:21
I'll leave the script I've used to generate unique ids here in case lipis/flag-icons will not be interested in PR.

```php
<?php

$files = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator(
        'svg',
        FilesystemIterator::SKIP_DOTS
    )
);

$rules = [
    '/ id="([a-z])"/' => ' id="{CODE}-$1"',
    '/ xlink:href="#([a-z])"/' => ' xlink:href="#{CODE}-$1"',
    '/"url\(#([a-z])\)"/' => '"url(#{CODE}-$1)"',
];

foreach ($files as $file) {
    $code = $file->getBasename('.svg');
    $fileObj = $file->openFile('r+');
    $contents = $fileObj->fread($file->getSize());

    $compiledRules = [];
    foreach ($rules as $key => $value) {
        $compiledRules[$key] = str_replace('{CODE}', $code, $value);
    }

    $contents = preg_replace(
        array_keys($compiledRules),
        array_values($compiledRules),
        $contents
    );

    $fileObj->rewind();
    $fileObj->fwrite($contents);
}

```

**Comment by vovayatsyuk** [comment] 2022-10-21 16:59
I've just tagged the new release. The issue should be fixed now.

**Closed as completed** 2022-10-26 16:30 UTC
